name: Check dist/index.js
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci

      - run: npm run build
      - name: Compare the expected and actual dist/index.js files
        run: |
          if [ "$(git diff --ignore-space-at-eol --ignore-cr-at-eol --ignore-blank-lines --text dist/index.js | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

      - uses: actions/upload-artifact@v3
        if: failure() && steps.diff.conclusion == 'failure'
        with:
          name: dist
          path: dist/
