name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run all
  test-single:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ndk-version: [r21e, r23]
        local-cache: [true, false]
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: install-ndk
        with:
          ndk-version: ${{ matrix.ndk-version }}
          local-cache: ${{ matrix.local-cache }}
      - run: ndk-build --version
      - run: ${{ steps.install-ndk.outputs.ndk-path }}/ndk-build --version
  test-multiple:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        local-cache: [true, false]
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: install-ndk-21
        with:
          ndk-version: r21e
          add-to-path: false
          local-cache: ${{ matrix.local-cache }}
      - uses: ./
        id: install-ndk-23
        with:
          ndk-version: r23
          add-to-path: false
          local-cache: ${{ matrix.local-cache }}
      - run: '! which ndk-build'
      - run: ${{ steps.install-ndk-21.outputs.ndk-path }}/ndk-build --version
      - run: ${{ steps.install-ndk-23.outputs.ndk-path }}/ndk-build --version
